### ISSUE TITLE
cannot find module 'it-is'

### ISSUE THREAD

**Issue by abbood** [max-mapper/conversationThreading-js#3]
whenever i run your program i get this error:

module.js:340
    throw err;
          ^
Error: Cannot find module 'it-is'

it's very hard to search for an 'it-is' module on google to be honest.. can you guys please show me where to get it? couldn't find any node.js unit test framework that fit the bill..

**Comment by tilgovi** [comment]
Looks like it's this: https://github.com/dominictarr/it-is
I recommend closing this issue in favor of #5.
